name = "barbearia-brooklyn"
compatibility_date = "2024-10-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "barbearia_brooklyn_db"
database_id = "d5d934a3-9a3e-4465-a3ee-c314b616990a"

[[kv_namespaces]]
binding = "KV_OAUTH"
id = "26cb4f82adf64592ac4fd803645e8715"

# Secrets (configurar via wrangler secret put):
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - FACEBOOK_CLIENT_ID
# - FACEBOOK_CLIENT_SECRET
# - INSTAGRAM_CLIENT_ID
# - INSTAGRAM_CLIENT_SECRET
BASE_URL = "brooklyn.tiagoanoliveira.pt"
# - JWT_SECRET