name = "barbearia-brooklyn"
compatibility_date = "2024-10-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "barbearia_brooklyn_db"
database_id = "60eb1712-958e-47af-88a9-311e565675c4"

[[kv_namespaces]]
binding = "KV_OAUTH"
id = "86af906265284b3290083b68816ac30b"

# Secrets (configurar via wrangler secret put):
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - FACEBOOK_CLIENT_ID
# - FACEBOOK_CLIENT_SECRET
# - INSTAGRAM_CLIENT_ID
# - INSTAGRAM_CLIENT_SECRET
# - BASE_URL = "brooklynbarbearia.pt"
# - JWT_SECRET